### PR TITLE
sru: 20.4.0 maas logs

### PR DESCRIPTION
**Pull request by blackboxsw**

### CODE REVIEW

**Review by lucasmoura — COMMENTED** [review]
Is it expected to not have logs for `groovy` ?

**Review by OddBloke — COMMENTED** [review]
I only see one test run here, which appears to be for bionic ("Ran 84 tests in 3004.189s"). Should there be more tests, or is this the extent of the downstream testing MAAS provides to us?

For retrospective/next time:

* this test appears to build a MAAS deb for testing (and is testing it using autopkgtest); as my understanding is that MAAS is distributed only as a snap now, I'm wondering if this is actually testing the latest version of MAAS
  * the version installed is `2.4.2-7034-g2f5deb8b8-0ubuntu1`, so maybe we're testing master here?
  * if that is the case, we shouldn't be skipping tests which _do_ apply to the version under test (which aren't currently being skipped because they don't apply to MAAS 2.4)
* in a similar vein, I see "running with Curtin from archive": `curtin` is no longer being SRU'd so using the version in the archive also means we aren't testing against the latest curtin version

**Comment by blackboxsw** [comment]
> I only see one test run here, which appears to be for bionic ("Ran 84 tests in 3004.189s"). Should there be more tests, or is this the extent of the downstream testing MAAS provides to us?

Hrm, a vague bell going off here that they were limiting their LTS versions under test in their integration framework, but that may have just been CDO QA which was only limiting theirs to bionic because that's the "cloud" Ubuntu series that we support from CDO QA for production offerings.

MAAS may have just tried to align with that, but it's worth a ping to them to confirm. I'll send the email


> 
> For retrospective/next time:
> 
>     * this test appears to build a MAAS deb for testing (and is testing it using autopkgtest); as my understanding is that MAAS is distributed only as a snap now, I'm wondering if this is actually testing the latest version of MAAS
>       
>       * the version installed is `2.4.2-7034-g2f5deb8b8-0ubuntu1`, so maybe we're testing master here?
>       * if that is the case, we shouldn't be skipping tests which _do_ apply to the version under test (which aren't currently being skipped because they don't apply to MAAS 2.4)
> 
>     * in a similar vein, I see "running with Curtin from archive": `curtin` is no longer being SRU'd so using the version in the archive also means we aren't testing against the latest curtin version

Yes, we really need to coordinate with the MAAS team to make sure these "gaps" are exposed here for next round. CDO QA test harness shouldn't be exposed to this issue (they just happen to use the *-proposed images that maas creates in their streams data.

**Comment by blackboxsw** [comment]
> I only see one test run here, which appears to be for bionic ("Ran 84 tests in 3004.189s"). Should there be more tests, or is this the extent of the downstream testing MAAS provides to us?


MAAS should be performing tests on every LTS for us in their smoke test. Though I think we may have dropped that specific requirement from our SRU template recently in https://wiki.ubuntu.com/CloudinitUpdates because MAAS ended up blocking release a few times. And given that CDO QA covers the base maas case test with more depth, we probably have the coverage we need from an SRU perspective if we get CDO QA runs.

Also a correction; the logs do show MAAS installing the proper cloud-init -proposed versions on each LTS here:
egrep cloud-init_ manual/maas-sru-20.4.0.txt
Preparing to unpack .../cloud-init_20.4-0ubuntu1~16.04.1_all.deb ...
Preparing to unpack .../10-cloud-init_20.4-0ubuntu1~18.04.1_all.deb ...
Preparing to unpack .../19-cloud-init_20.4-0ubuntu1~20.04.1_all.deb ...

So I think we are getting exercise on all LTS flavors for cloud-init, you may only be seeing MAAS being setup on a bionic system as the maas host in that test run.

I see them doing some image setup like the following, which ends up pulling in the cloud-init for the right LTS flavor

2020-12-10 06:28:45 (2.73 MB/s) - ‘/tmp/maas-cloudimg2eph2.8pvBjs/xenial-server-cloudimg-amd64.squashfs’ saved [178307072/178307072]
Thu, 10 Dec 2020 06:44:07 +0000: getting source http://cloud-images.ubuntu.com/daily/server/bionic/20201209/bionic-server-cloudimg-amd64.squashfs
Thu, 10 Dec 2020 07:01:14 +0000: getting source http://cloud-images.ubuntu.com/daily/server/focal/20201201/focal-server-cloudimg-amd64.squashfs

**Comment by OddBloke** [comment]
Thanks for checking that, Chad.

**Pull request merged**
